"""add Comment.reply_to

Revision ID: 4c00c86bb232
Revises: fc43a392dd2f
Create Date: 2017-05-12 11:27:52.511462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c00c86bb232'
down_revision = 'fc43a392dd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_to', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'reply_to')
    # ### end Alembic commands ###
