"""del Article.summary

Revision ID: d9e0854c209e
Revises: 4c00c86bb232
Create Date: 2017-05-12 16:26:29.308424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e0854c209e'
down_revision = '4c00c86bb232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('articles', 'summary')
    with op.batch_alter_table('articles') as batch_op:
        batch_op.drop_column('summary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('summary', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
